name: Maria Kubin
favicon: null
layout_spectrum: 1
typography_spectrum: 0.012367052724584937
title: Psychotherapie Kubin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff7a7c'
    - '#ff4229'
    - '#533b3d'
    - '#ffda6e'
    - '#8a9ba1'
  brandStrength: 0.937822473468259
  lightness: 0.9058245474006981
  saturation: 0.24225394311361015
  rhythmicContrast: 0.990302543155849
purpose: []
