name: Maria Kubin
favicon: null
layout_spectrum: 0.50339
typography_spectrum: 0.50792
title: Psychotherapie Kubin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#fefefe'
    - '#385600'
    - '#92e101'
    - '#c3b47e'
  brandStrength: 0.937822473468259
  lightness: 0.9058245474006981
  saturation: 0.24225394311361015
  rhythmicContrast: 0.990302543155849
purpose: []
